<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/client_events.php');
	include_once(__DIR__ . '/client_events_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('client_events');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'client_events';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`client_events`.`id`" => "id",
		"if(`client_events`.`datetime`,date_format(`client_events`.`datetime`,'%d/%m/%Y %h:%i %p'),'')" => "datetime",
		"IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') /* Client */" => "client",
		"`client_events`.`event`" => "event",
		"`client_events`.`details`" => "details",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`client_events`.`id`',
		2 => '`client_events`.`datetime`',
		3 => '`clients1`.`client`',
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`client_events`.`id`" => "id",
		"if(`client_events`.`datetime`,date_format(`client_events`.`datetime`,'%d/%m/%Y %h:%i %p'),'')" => "datetime",
		"IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') /* Client */" => "client",
		"`client_events`.`event`" => "event",
		"`client_events`.`details`" => "details",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`client_events`.`id`" => "ID",
		"`client_events`.`datetime`" => "Datetime",
		"IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') /* Client */" => "Client",
		"`client_events`.`event`" => "Event",
		"`client_events`.`details`" => "Details",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`client_events`.`id`" => "id",
		"if(`client_events`.`datetime`,date_format(`client_events`.`datetime`,'%d/%m/%Y %h:%i %p'),'')" => "datetime",
		"IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') /* Client */" => "client",
		"`client_events`.`event`" => "event",
		"`client_events`.`details`" => "details",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['client' => 'Client', ];

	$x->QueryFrom = "`client_events` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`client_events`.`client` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'client_events_view.php';
	$x->RedirectAfterInsert = 'client_events_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Client events';
	$x->TableIcon = 'resources/table_icons/file_extension_log.png';
	$x->PrimaryKey = '`client_events`.`id`';
	$x->DefaultSortField = '`client_events`.`datetime`';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Datetime', 'Client', 'Event', 'Details', ];
	$x->ColFieldName = ['datetime', 'client', 'event', 'details', ];
	$x->ColNumber  = [2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/client_events_templateTV.html';
	$x->SelectedTemplate = 'templates/client_events_templateTVS.html';
	$x->TemplateDV = 'templates/client_events_templateDV.html';
	$x->TemplateDVP = 'templates/client_events_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: client_events_init
	$render = true;
	if(function_exists('client_events_init')) {
		$args = [];
		$render = client_events_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: client_events_header
	$headerCode = '';
	if(function_exists('client_events_header')) {
		$args = [];
		$headerCode = client_events_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: client_events_footer
	$footerCode = '';
	if(function_exists('client_events_footer')) {
		$args = [];
		$footerCode = client_events_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
