<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/data_centers.php');
	include_once(__DIR__ . '/data_centers_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('data_centers');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'data_centers';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`data_centers`.`id`" => "id",
		"IF(    CHAR_LENGTH(`hosting_providers1`.`hosting_provider`), CONCAT_WS('',   `hosting_providers1`.`hosting_provider`), '') /* Hosting provider */" => "hosting_provider",
		"`data_centers`.`data_center`" => "data_center",
		"`data_centers`.`comments`" => "comments",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`data_centers`.`id`',
		2 => '`hosting_providers1`.`hosting_provider`',
		3 => 3,
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`data_centers`.`id`" => "id",
		"IF(    CHAR_LENGTH(`hosting_providers1`.`hosting_provider`), CONCAT_WS('',   `hosting_providers1`.`hosting_provider`), '') /* Hosting provider */" => "hosting_provider",
		"`data_centers`.`data_center`" => "data_center",
		"`data_centers`.`comments`" => "comments",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`data_centers`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`hosting_providers1`.`hosting_provider`), CONCAT_WS('',   `hosting_providers1`.`hosting_provider`), '') /* Hosting provider */" => "Hosting provider",
		"`data_centers`.`data_center`" => "Data center",
		"`data_centers`.`comments`" => "Comments",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`data_centers`.`id`" => "id",
		"IF(    CHAR_LENGTH(`hosting_providers1`.`hosting_provider`), CONCAT_WS('',   `hosting_providers1`.`hosting_provider`), '') /* Hosting provider */" => "hosting_provider",
		"`data_centers`.`data_center`" => "data_center",
		"`data_centers`.`comments`" => "comments",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['hosting_provider' => 'Hosting provider', ];

	$x->QueryFrom = "`data_centers` LEFT JOIN `hosting_providers` as hosting_providers1 ON `hosting_providers1`.`id`=`data_centers`.`hosting_provider` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'data_centers_view.php';
	$x->RedirectAfterInsert = 'data_centers_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Data centers';
	$x->TableIcon = 'resources/table_icons/server_stanchion.png';
	$x->PrimaryKey = '`data_centers`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Hosting provider', 'Data center', ];
	$x->ColFieldName = ['hosting_provider', 'data_center', ];
	$x->ColNumber  = [2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/data_centers_templateTV.html';
	$x->SelectedTemplate = 'templates/data_centers_templateTVS.html';
	$x->TemplateDV = 'templates/data_centers_templateDV.html';
	$x->TemplateDVP = 'templates/data_centers_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "col-lg-4";
	$x->DVClasses = "col-lg-8";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: data_centers_init
	$render = true;
	if(function_exists('data_centers_init')) {
		$args = [];
		$render = data_centers_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: data_centers_header
	$headerCode = '';
	if(function_exists('data_centers_header')) {
		$args = [];
		$headerCode = data_centers_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: data_centers_footer
	$footerCode = '';
	if(function_exists('data_centers_footer')) {
		$args = [];
		$footerCode = data_centers_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
