<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/domains.php');
	include_once(__DIR__ . '/domains_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('domains');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'domains';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`domains`.`domain_name`" => "domain_name",
		"concat('<i class=\"glyphicon glyphicon-', if(`domains`.`expired`, 'check', 'unchecked'), '\"></i>')" => "expired",
		"IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') /* Client */" => "client",
		"IF(    CHAR_LENGTH(`registrars1`.`registrar`), CONCAT_WS('',   `registrars1`.`registrar`), '') /* Registrar */" => "registrar",
		"IF(    CHAR_LENGTH(`dns_managers1`.`dns_manager`), CONCAT_WS('',   `dns_managers1`.`dns_manager`), '') /* DNS manager */" => "dns_manager",
		"IF(    CHAR_LENGTH(`mail_providers1`.`mail_provider`), CONCAT_WS('',   `mail_providers1`.`mail_provider`), '') /* Mail provider */" => "mail_provider",
		"if(`domains`.`registration_date`,date_format(`domains`.`registration_date`,'%d/%m/%Y'),'')" => "registration_date",
		"if(`domains`.`next_renewal_date`,date_format(`domains`.`next_renewal_date`,'%d/%m/%Y'),'')" => "next_renewal_date",
		"`domains`.`comments`" => "comments",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => '`domains`.`expired`',
		3 => '`clients1`.`client`',
		4 => '`registrars1`.`registrar`',
		5 => '`dns_managers1`.`dns_manager`',
		6 => '`mail_providers1`.`mail_provider`',
		7 => '`domains`.`registration_date`',
		8 => '`domains`.`next_renewal_date`',
		9 => 9,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`domains`.`domain_name`" => "domain_name",
		"`domains`.`expired`" => "expired",
		"IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') /* Client */" => "client",
		"IF(    CHAR_LENGTH(`registrars1`.`registrar`), CONCAT_WS('',   `registrars1`.`registrar`), '') /* Registrar */" => "registrar",
		"IF(    CHAR_LENGTH(`dns_managers1`.`dns_manager`), CONCAT_WS('',   `dns_managers1`.`dns_manager`), '') /* DNS manager */" => "dns_manager",
		"IF(    CHAR_LENGTH(`mail_providers1`.`mail_provider`), CONCAT_WS('',   `mail_providers1`.`mail_provider`), '') /* Mail provider */" => "mail_provider",
		"if(`domains`.`registration_date`,date_format(`domains`.`registration_date`,'%d/%m/%Y'),'')" => "registration_date",
		"if(`domains`.`next_renewal_date`,date_format(`domains`.`next_renewal_date`,'%d/%m/%Y'),'')" => "next_renewal_date",
		"`domains`.`comments`" => "comments",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`domains`.`domain_name`" => "Domain name",
		"`domains`.`expired`" => "Expired",
		"IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') /* Client */" => "Client",
		"IF(    CHAR_LENGTH(`registrars1`.`registrar`), CONCAT_WS('',   `registrars1`.`registrar`), '') /* Registrar */" => "Registrar",
		"IF(    CHAR_LENGTH(`dns_managers1`.`dns_manager`), CONCAT_WS('',   `dns_managers1`.`dns_manager`), '') /* DNS manager */" => "DNS manager",
		"IF(    CHAR_LENGTH(`mail_providers1`.`mail_provider`), CONCAT_WS('',   `mail_providers1`.`mail_provider`), '') /* Mail provider */" => "Mail provider",
		"`domains`.`registration_date`" => "Registration date",
		"`domains`.`next_renewal_date`" => "Next renewal date",
		"`domains`.`comments`" => "Comments",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`domains`.`domain_name`" => "domain_name",
		"concat('<i class=\"glyphicon glyphicon-', if(`domains`.`expired`, 'check', 'unchecked'), '\"></i>')" => "expired",
		"IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') /* Client */" => "client",
		"IF(    CHAR_LENGTH(`registrars1`.`registrar`), CONCAT_WS('',   `registrars1`.`registrar`), '') /* Registrar */" => "registrar",
		"IF(    CHAR_LENGTH(`dns_managers1`.`dns_manager`), CONCAT_WS('',   `dns_managers1`.`dns_manager`), '') /* DNS manager */" => "dns_manager",
		"IF(    CHAR_LENGTH(`mail_providers1`.`mail_provider`), CONCAT_WS('',   `mail_providers1`.`mail_provider`), '') /* Mail provider */" => "mail_provider",
		"if(`domains`.`registration_date`,date_format(`domains`.`registration_date`,'%d/%m/%Y'),'')" => "registration_date",
		"if(`domains`.`next_renewal_date`,date_format(`domains`.`next_renewal_date`,'%d/%m/%Y'),'')" => "next_renewal_date",
		"`domains`.`comments`" => "comments",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['client' => 'Client', 'registrar' => 'Registrar', 'dns_manager' => 'DNS manager', 'mail_provider' => 'Mail provider', ];

	$x->QueryFrom = "`domains` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`domains`.`client` LEFT JOIN `registrars` as registrars1 ON `registrars1`.`id`=`domains`.`registrar` LEFT JOIN `dns_managers` as dns_managers1 ON `dns_managers1`.`id`=`domains`.`dns_manager` LEFT JOIN `mail_providers` as mail_providers1 ON `mail_providers1`.`id`=`domains`.`mail_provider` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'domains_view.php';
	$x->RedirectAfterInsert = 'domains_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Domains';
	$x->TableIcon = 'resources/table_icons/domain_template.png';
	$x->PrimaryKey = '`domains`.`domain_name`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Domain name', 'Expired', 'Client', 'Registrar', 'DNS manager', 'Mail provider', 'Registration date', 'Next renewal date', ];
	$x->ColFieldName = ['domain_name', 'expired', 'client', 'registrar', 'dns_manager', 'mail_provider', 'registration_date', 'next_renewal_date', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/domains_templateTV.html';
	$x->SelectedTemplate = 'templates/domains_templateTVS.html';
	$x->TemplateDV = 'templates/domains_templateDV.html';
	$x->TemplateDVP = 'templates/domains_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: domains_init
	$render = true;
	if(function_exists('domains_init')) {
		$args = [];
		$render = domains_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: domains_header
	$headerCode = '';
	if(function_exists('domains_header')) {
		$args = [];
		$headerCode = domains_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: domains_footer
	$footerCode = '';
	if(function_exists('domains_footer')) {
		$args = [];
		$footerCode = domains_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
