<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/operating_systems.php');
	include_once(__DIR__ . '/operating_systems_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('operating_systems');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'operating_systems';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`operating_systems`.`id`" => "id",
		"`operating_systems`.`operating_system`" => "operating_system",
		"`operating_systems`.`comments`" => "comments",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`operating_systems`.`id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`operating_systems`.`id`" => "id",
		"`operating_systems`.`operating_system`" => "operating_system",
		"`operating_systems`.`comments`" => "comments",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`operating_systems`.`id`" => "ID",
		"`operating_systems`.`operating_system`" => "OS",
		"`operating_systems`.`comments`" => "Comments",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`operating_systems`.`id`" => "id",
		"`operating_systems`.`operating_system`" => "operating_system",
		"`operating_systems`.`comments`" => "comments",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`operating_systems` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 25;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'operating_systems_view.php';
	$x->RedirectAfterInsert = 'operating_systems_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Operating systems';
	$x->TableIcon = 'resources/table_icons/download_for_linux.png';
	$x->PrimaryKey = '`operating_systems`.`id`';
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, ];
	$x->ColCaption = ['OS', ];
	$x->ColFieldName = ['operating_system', ];
	$x->ColNumber  = [2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/operating_systems_templateTV.html';
	$x->SelectedTemplate = 'templates/operating_systems_templateTVS.html';
	$x->TemplateDV = 'templates/operating_systems_templateDV.html';
	$x->TemplateDVP = 'templates/operating_systems_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "col-lg-3";
	$x->DVClasses = "col-lg-9";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: operating_systems_init
	$render = true;
	if(function_exists('operating_systems_init')) {
		$args = [];
		$render = operating_systems_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: operating_systems_header
	$headerCode = '';
	if(function_exists('operating_systems_header')) {
		$args = [];
		$headerCode = operating_systems_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: operating_systems_footer
	$footerCode = '';
	if(function_exists('operating_systems_footer')) {
		$args = [];
		$footerCode = operating_systems_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
