<?php
// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	/* Configuration */
	/*************************************/

		$pcConfig = [
			'servers' => [
				'client' => [
					'parent-table' => 'clients',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Servers <span class="hidden child-label-servers child-field-caption">(Client)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/server.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'IP address', 2 => 'Client', 3 => 'Hosted at', 4 => 'Data center', 5 => 'Hostname', 6 => 'RAM (GB)', 7 => 'Storage (GB)', 8 => 'OS', 9 => 'Comments'],
					'display-field-names' => [1 => 'ip_address', 2 => 'client', 3 => 'hosted_at', 4 => 'data_center', 5 => 'hostname', 6 => 'ram', 7 => 'storage', 8 => 'os', 9 => 'comments'],
					'sortable-fields' => [0 => '`servers`.`id`', 1 => 2, 2 => '`clients1`.`client`', 3 => '`hosting_providers1`.`hosting_provider`', 4 => '`data_centers1`.`data_center`', 5 => 6, 6 => '`servers`.`ram`', 7 => '`servers`.`storage`', 8 => '`operating_systems1`.`operating_system`', 9 => 10],
					'records-per-page' => 10,
					'default-sort-by' => 0,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-servers',
					'template-printable' => 'children-servers-printable',
					'query' => "SELECT `servers`.`id` as 'id', `servers`.`ip_address` as 'ip_address', IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') as 'client', IF(    CHAR_LENGTH(`hosting_providers1`.`hosting_provider`), CONCAT_WS('',   `hosting_providers1`.`hosting_provider`), '') as 'hosted_at', IF(    CHAR_LENGTH(`data_centers1`.`data_center`), CONCAT_WS('',   `data_centers1`.`data_center`), '') as 'data_center', `servers`.`hostname` as 'hostname', `servers`.`ram` as 'ram', `servers`.`storage` as 'storage', IF(    CHAR_LENGTH(`operating_systems1`.`operating_system`), CONCAT_WS('',   `operating_systems1`.`operating_system`), '') as 'os', `servers`.`comments` as 'comments' FROM `servers` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`servers`.`client` LEFT JOIN `hosting_providers` as hosting_providers1 ON `hosting_providers1`.`id`=`servers`.`hosted_at` LEFT JOIN `data_centers` as data_centers1 ON `data_centers1`.`id`=`servers`.`data_center` LEFT JOIN `operating_systems` as operating_systems1 ON `operating_systems1`.`id`=`servers`.`os` "
				],
				'hosted_at' => [
					'parent-table' => 'hosting_providers',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Servers <span class="hidden child-label-servers child-field-caption">(Hosted at)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/server.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'IP address', 2 => 'Client', 3 => 'Hosted at', 4 => 'Data center', 5 => 'Hostname', 6 => 'RAM (GB)', 7 => 'Storage (GB)', 8 => 'OS', 9 => 'Comments'],
					'display-field-names' => [1 => 'ip_address', 2 => 'client', 3 => 'hosted_at', 4 => 'data_center', 5 => 'hostname', 6 => 'ram', 7 => 'storage', 8 => 'os', 9 => 'comments'],
					'sortable-fields' => [0 => '`servers`.`id`', 1 => 2, 2 => '`clients1`.`client`', 3 => '`hosting_providers1`.`hosting_provider`', 4 => '`data_centers1`.`data_center`', 5 => 6, 6 => '`servers`.`ram`', 7 => '`servers`.`storage`', 8 => '`operating_systems1`.`operating_system`', 9 => 10],
					'records-per-page' => 10,
					'default-sort-by' => 0,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-servers',
					'template-printable' => 'children-servers-printable',
					'query' => "SELECT `servers`.`id` as 'id', `servers`.`ip_address` as 'ip_address', IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') as 'client', IF(    CHAR_LENGTH(`hosting_providers1`.`hosting_provider`), CONCAT_WS('',   `hosting_providers1`.`hosting_provider`), '') as 'hosted_at', IF(    CHAR_LENGTH(`data_centers1`.`data_center`), CONCAT_WS('',   `data_centers1`.`data_center`), '') as 'data_center', `servers`.`hostname` as 'hostname', `servers`.`ram` as 'ram', `servers`.`storage` as 'storage', IF(    CHAR_LENGTH(`operating_systems1`.`operating_system`), CONCAT_WS('',   `operating_systems1`.`operating_system`), '') as 'os', `servers`.`comments` as 'comments' FROM `servers` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`servers`.`client` LEFT JOIN `hosting_providers` as hosting_providers1 ON `hosting_providers1`.`id`=`servers`.`hosted_at` LEFT JOIN `data_centers` as data_centers1 ON `data_centers1`.`id`=`servers`.`data_center` LEFT JOIN `operating_systems` as operating_systems1 ON `operating_systems1`.`id`=`servers`.`os` "
				],
				'data_center' => [
					'parent-table' => 'data_centers',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Servers <span class="hidden child-label-servers child-field-caption">(Data center)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/server.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'IP address', 2 => 'Client', 3 => 'Hosted at', 4 => 'Data center', 5 => 'Hostname', 6 => 'RAM (GB)', 7 => 'Storage (GB)', 8 => 'OS', 9 => 'Comments'],
					'display-field-names' => [1 => 'ip_address', 2 => 'client', 3 => 'hosted_at', 4 => 'data_center', 5 => 'hostname', 6 => 'ram', 7 => 'storage', 8 => 'os', 9 => 'comments'],
					'sortable-fields' => [0 => '`servers`.`id`', 1 => 2, 2 => '`clients1`.`client`', 3 => '`hosting_providers1`.`hosting_provider`', 4 => '`data_centers1`.`data_center`', 5 => 6, 6 => '`servers`.`ram`', 7 => '`servers`.`storage`', 8 => '`operating_systems1`.`operating_system`', 9 => 10],
					'records-per-page' => 10,
					'default-sort-by' => 0,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-servers',
					'template-printable' => 'children-servers-printable',
					'query' => "SELECT `servers`.`id` as 'id', `servers`.`ip_address` as 'ip_address', IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') as 'client', IF(    CHAR_LENGTH(`hosting_providers1`.`hosting_provider`), CONCAT_WS('',   `hosting_providers1`.`hosting_provider`), '') as 'hosted_at', IF(    CHAR_LENGTH(`data_centers1`.`data_center`), CONCAT_WS('',   `data_centers1`.`data_center`), '') as 'data_center', `servers`.`hostname` as 'hostname', `servers`.`ram` as 'ram', `servers`.`storage` as 'storage', IF(    CHAR_LENGTH(`operating_systems1`.`operating_system`), CONCAT_WS('',   `operating_systems1`.`operating_system`), '') as 'os', `servers`.`comments` as 'comments' FROM `servers` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`servers`.`client` LEFT JOIN `hosting_providers` as hosting_providers1 ON `hosting_providers1`.`id`=`servers`.`hosted_at` LEFT JOIN `data_centers` as data_centers1 ON `data_centers1`.`id`=`servers`.`data_center` LEFT JOIN `operating_systems` as operating_systems1 ON `operating_systems1`.`id`=`servers`.`os` "
				],
				'os' => [
					'parent-table' => 'operating_systems',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Servers <span class="hidden child-label-servers child-field-caption">(OS)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/server.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'IP address', 2 => 'Client', 3 => 'Hosted at', 4 => 'Data center', 5 => 'Hostname', 6 => 'RAM (GB)', 7 => 'Storage (GB)', 8 => 'OS', 9 => 'Comments'],
					'display-field-names' => [1 => 'ip_address', 2 => 'client', 3 => 'hosted_at', 4 => 'data_center', 5 => 'hostname', 6 => 'ram', 7 => 'storage', 8 => 'os', 9 => 'comments'],
					'sortable-fields' => [0 => '`servers`.`id`', 1 => 2, 2 => '`clients1`.`client`', 3 => '`hosting_providers1`.`hosting_provider`', 4 => '`data_centers1`.`data_center`', 5 => 6, 6 => '`servers`.`ram`', 7 => '`servers`.`storage`', 8 => '`operating_systems1`.`operating_system`', 9 => 10],
					'records-per-page' => 10,
					'default-sort-by' => 0,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-servers',
					'template-printable' => 'children-servers-printable',
					'query' => "SELECT `servers`.`id` as 'id', `servers`.`ip_address` as 'ip_address', IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') as 'client', IF(    CHAR_LENGTH(`hosting_providers1`.`hosting_provider`), CONCAT_WS('',   `hosting_providers1`.`hosting_provider`), '') as 'hosted_at', IF(    CHAR_LENGTH(`data_centers1`.`data_center`), CONCAT_WS('',   `data_centers1`.`data_center`), '') as 'data_center', `servers`.`hostname` as 'hostname', `servers`.`ram` as 'ram', `servers`.`storage` as 'storage', IF(    CHAR_LENGTH(`operating_systems1`.`operating_system`), CONCAT_WS('',   `operating_systems1`.`operating_system`), '') as 'os', `servers`.`comments` as 'comments' FROM `servers` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`servers`.`client` LEFT JOIN `hosting_providers` as hosting_providers1 ON `hosting_providers1`.`id`=`servers`.`hosted_at` LEFT JOIN `data_centers` as data_centers1 ON `data_centers1`.`id`=`servers`.`data_center` LEFT JOIN `operating_systems` as operating_systems1 ON `operating_systems1`.`id`=`servers`.`os` "
				],
			],
			'operating_systems' => [
			],
			'hosting_providers' => [
			],
			'data_centers' => [
				'hosting_provider' => [
					'parent-table' => 'hosting_providers',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Data centers <span class="hidden child-label-data_centers child-field-caption">(Hosting provider)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/server_stanchion.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'Hosting provider', 2 => 'Data center'],
					'display-field-names' => [1 => 'hosting_provider', 2 => 'data_center'],
					'sortable-fields' => [0 => '`data_centers`.`id`', 1 => '`hosting_providers1`.`hosting_provider`', 2 => 3, 3 => 4],
					'records-per-page' => 10,
					'default-sort-by' => 0,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-data_centers',
					'template-printable' => 'children-data_centers-printable',
					'query' => "SELECT `data_centers`.`id` as 'id', IF(    CHAR_LENGTH(`hosting_providers1`.`hosting_provider`), CONCAT_WS('',   `hosting_providers1`.`hosting_provider`), '') as 'hosting_provider', `data_centers`.`data_center` as 'data_center', `data_centers`.`comments` as 'comments' FROM `data_centers` LEFT JOIN `hosting_providers` as hosting_providers1 ON `hosting_providers1`.`id`=`data_centers`.`hosting_provider` "
				],
			],
			'domains' => [
				'client' => [
					'parent-table' => 'clients',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'domain_name',
					'child-primary-key-index' => 0,
					'tab-label' => 'Domains <span class="hidden child-label-domains child-field-caption">(Client)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/domain_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [0 => 'Domain name', 1 => 'Expired', 2 => 'Client', 3 => 'Registrar', 4 => 'DNS manager', 5 => 'Mail provider', 6 => 'Registration date', 7 => 'Next renewal date'],
					'display-field-names' => [0 => 'domain_name', 1 => 'expired', 2 => 'client', 3 => 'registrar', 4 => 'dns_manager', 5 => 'mail_provider', 6 => 'registration_date', 7 => 'next_renewal_date'],
					'sortable-fields' => [0 => 1, 1 => '`domains`.`expired`', 2 => '`clients1`.`client`', 3 => '`registrars1`.`registrar`', 4 => '`dns_managers1`.`dns_manager`', 5 => '`mail_providers1`.`mail_provider`', 6 => '`domains`.`registration_date`', 7 => '`domains`.`next_renewal_date`', 8 => 9],
					'records-per-page' => 10,
					'default-sort-by' => 0,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-domains',
					'template-printable' => 'children-domains-printable',
					'query' => "SELECT `domains`.`domain_name` as 'domain_name', concat('<i class=\"glyphicon glyphicon-', if(`domains`.`expired`, 'check', 'unchecked'), '\"></i>') as 'expired', IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') as 'client', IF(    CHAR_LENGTH(`registrars1`.`registrar`), CONCAT_WS('',   `registrars1`.`registrar`), '') as 'registrar', IF(    CHAR_LENGTH(`dns_managers1`.`dns_manager`), CONCAT_WS('',   `dns_managers1`.`dns_manager`), '') as 'dns_manager', IF(    CHAR_LENGTH(`mail_providers1`.`mail_provider`), CONCAT_WS('',   `mail_providers1`.`mail_provider`), '') as 'mail_provider', if(`domains`.`registration_date`,date_format(`domains`.`registration_date`,'%d/%m/%Y'),'') as 'registration_date', if(`domains`.`next_renewal_date`,date_format(`domains`.`next_renewal_date`,'%d/%m/%Y'),'') as 'next_renewal_date', `domains`.`comments` as 'comments' FROM `domains` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`domains`.`client` LEFT JOIN `registrars` as registrars1 ON `registrars1`.`id`=`domains`.`registrar` LEFT JOIN `dns_managers` as dns_managers1 ON `dns_managers1`.`id`=`domains`.`dns_manager` LEFT JOIN `mail_providers` as mail_providers1 ON `mail_providers1`.`id`=`domains`.`mail_provider` "
				],
				'registrar' => [
					'parent-table' => 'registrars',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'domain_name',
					'child-primary-key-index' => 0,
					'tab-label' => 'Domains <span class="hidden child-label-domains child-field-caption">(Registrar)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/domain_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [0 => 'Domain name', 1 => 'Expired', 2 => 'Client', 3 => 'Registrar', 4 => 'DNS manager', 5 => 'Mail provider', 6 => 'Registration date', 7 => 'Next renewal date'],
					'display-field-names' => [0 => 'domain_name', 1 => 'expired', 2 => 'client', 3 => 'registrar', 4 => 'dns_manager', 5 => 'mail_provider', 6 => 'registration_date', 7 => 'next_renewal_date'],
					'sortable-fields' => [0 => 1, 1 => '`domains`.`expired`', 2 => '`clients1`.`client`', 3 => '`registrars1`.`registrar`', 4 => '`dns_managers1`.`dns_manager`', 5 => '`mail_providers1`.`mail_provider`', 6 => '`domains`.`registration_date`', 7 => '`domains`.`next_renewal_date`', 8 => 9],
					'records-per-page' => 10,
					'default-sort-by' => 0,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-domains',
					'template-printable' => 'children-domains-printable',
					'query' => "SELECT `domains`.`domain_name` as 'domain_name', concat('<i class=\"glyphicon glyphicon-', if(`domains`.`expired`, 'check', 'unchecked'), '\"></i>') as 'expired', IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') as 'client', IF(    CHAR_LENGTH(`registrars1`.`registrar`), CONCAT_WS('',   `registrars1`.`registrar`), '') as 'registrar', IF(    CHAR_LENGTH(`dns_managers1`.`dns_manager`), CONCAT_WS('',   `dns_managers1`.`dns_manager`), '') as 'dns_manager', IF(    CHAR_LENGTH(`mail_providers1`.`mail_provider`), CONCAT_WS('',   `mail_providers1`.`mail_provider`), '') as 'mail_provider', if(`domains`.`registration_date`,date_format(`domains`.`registration_date`,'%d/%m/%Y'),'') as 'registration_date', if(`domains`.`next_renewal_date`,date_format(`domains`.`next_renewal_date`,'%d/%m/%Y'),'') as 'next_renewal_date', `domains`.`comments` as 'comments' FROM `domains` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`domains`.`client` LEFT JOIN `registrars` as registrars1 ON `registrars1`.`id`=`domains`.`registrar` LEFT JOIN `dns_managers` as dns_managers1 ON `dns_managers1`.`id`=`domains`.`dns_manager` LEFT JOIN `mail_providers` as mail_providers1 ON `mail_providers1`.`id`=`domains`.`mail_provider` "
				],
				'dns_manager' => [
					'parent-table' => 'dns_managers',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'domain_name',
					'child-primary-key-index' => 0,
					'tab-label' => 'Domains <span class="hidden child-label-domains child-field-caption">(DNS manager)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/domain_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [0 => 'Domain name', 1 => 'Expired', 2 => 'Client', 3 => 'Registrar', 4 => 'DNS manager', 5 => 'Mail provider', 6 => 'Registration date', 7 => 'Next renewal date'],
					'display-field-names' => [0 => 'domain_name', 1 => 'expired', 2 => 'client', 3 => 'registrar', 4 => 'dns_manager', 5 => 'mail_provider', 6 => 'registration_date', 7 => 'next_renewal_date'],
					'sortable-fields' => [0 => 1, 1 => '`domains`.`expired`', 2 => '`clients1`.`client`', 3 => '`registrars1`.`registrar`', 4 => '`dns_managers1`.`dns_manager`', 5 => '`mail_providers1`.`mail_provider`', 6 => '`domains`.`registration_date`', 7 => '`domains`.`next_renewal_date`', 8 => 9],
					'records-per-page' => 10,
					'default-sort-by' => 0,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-domains',
					'template-printable' => 'children-domains-printable',
					'query' => "SELECT `domains`.`domain_name` as 'domain_name', concat('<i class=\"glyphicon glyphicon-', if(`domains`.`expired`, 'check', 'unchecked'), '\"></i>') as 'expired', IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') as 'client', IF(    CHAR_LENGTH(`registrars1`.`registrar`), CONCAT_WS('',   `registrars1`.`registrar`), '') as 'registrar', IF(    CHAR_LENGTH(`dns_managers1`.`dns_manager`), CONCAT_WS('',   `dns_managers1`.`dns_manager`), '') as 'dns_manager', IF(    CHAR_LENGTH(`mail_providers1`.`mail_provider`), CONCAT_WS('',   `mail_providers1`.`mail_provider`), '') as 'mail_provider', if(`domains`.`registration_date`,date_format(`domains`.`registration_date`,'%d/%m/%Y'),'') as 'registration_date', if(`domains`.`next_renewal_date`,date_format(`domains`.`next_renewal_date`,'%d/%m/%Y'),'') as 'next_renewal_date', `domains`.`comments` as 'comments' FROM `domains` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`domains`.`client` LEFT JOIN `registrars` as registrars1 ON `registrars1`.`id`=`domains`.`registrar` LEFT JOIN `dns_managers` as dns_managers1 ON `dns_managers1`.`id`=`domains`.`dns_manager` LEFT JOIN `mail_providers` as mail_providers1 ON `mail_providers1`.`id`=`domains`.`mail_provider` "
				],
				'mail_provider' => [
					'parent-table' => 'mail_providers',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'domain_name',
					'child-primary-key-index' => 0,
					'tab-label' => 'Domains <span class="hidden child-label-domains child-field-caption">(Mail provider)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/domain_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [0 => 'Domain name', 1 => 'Expired', 2 => 'Client', 3 => 'Registrar', 4 => 'DNS manager', 5 => 'Mail provider', 6 => 'Registration date', 7 => 'Next renewal date'],
					'display-field-names' => [0 => 'domain_name', 1 => 'expired', 2 => 'client', 3 => 'registrar', 4 => 'dns_manager', 5 => 'mail_provider', 6 => 'registration_date', 7 => 'next_renewal_date'],
					'sortable-fields' => [0 => 1, 1 => '`domains`.`expired`', 2 => '`clients1`.`client`', 3 => '`registrars1`.`registrar`', 4 => '`dns_managers1`.`dns_manager`', 5 => '`mail_providers1`.`mail_provider`', 6 => '`domains`.`registration_date`', 7 => '`domains`.`next_renewal_date`', 8 => 9],
					'records-per-page' => 10,
					'default-sort-by' => 0,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-domains',
					'template-printable' => 'children-domains-printable',
					'query' => "SELECT `domains`.`domain_name` as 'domain_name', concat('<i class=\"glyphicon glyphicon-', if(`domains`.`expired`, 'check', 'unchecked'), '\"></i>') as 'expired', IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') as 'client', IF(    CHAR_LENGTH(`registrars1`.`registrar`), CONCAT_WS('',   `registrars1`.`registrar`), '') as 'registrar', IF(    CHAR_LENGTH(`dns_managers1`.`dns_manager`), CONCAT_WS('',   `dns_managers1`.`dns_manager`), '') as 'dns_manager', IF(    CHAR_LENGTH(`mail_providers1`.`mail_provider`), CONCAT_WS('',   `mail_providers1`.`mail_provider`), '') as 'mail_provider', if(`domains`.`registration_date`,date_format(`domains`.`registration_date`,'%d/%m/%Y'),'') as 'registration_date', if(`domains`.`next_renewal_date`,date_format(`domains`.`next_renewal_date`,'%d/%m/%Y'),'') as 'next_renewal_date', `domains`.`comments` as 'comments' FROM `domains` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`domains`.`client` LEFT JOIN `registrars` as registrars1 ON `registrars1`.`id`=`domains`.`registrar` LEFT JOIN `dns_managers` as dns_managers1 ON `dns_managers1`.`id`=`domains`.`dns_manager` LEFT JOIN `mail_providers` as mail_providers1 ON `mail_providers1`.`id`=`domains`.`mail_provider` "
				],
			],
			'subdomains' => [
				'domain' => [
					'parent-table' => 'domains',
					'parent-primary-key' => 'domain_name',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Subdomains <span class="hidden child-label-subdomains child-field-caption">(Domain)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/domain_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'Subdomain', 2 => 'Domain', 3 => 'Server', 4 => 'Comments'],
					'display-field-names' => [1 => 'subdomain', 2 => 'domain', 3 => 'server', 4 => 'comments'],
					'sortable-fields' => [0 => '`subdomains`.`id`', 1 => 2, 2 => '`domains1`.`domain_name`', 3 => '`servers1`.`hostname`', 4 => 5],
					'records-per-page' => 10,
					'default-sort-by' => 2,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-subdomains',
					'template-printable' => 'children-subdomains-printable',
					'query' => "SELECT `subdomains`.`id` as 'id', `subdomains`.`subdomain` as 'subdomain', IF(    CHAR_LENGTH(`domains1`.`domain_name`), CONCAT_WS('',   `domains1`.`domain_name`), '') as 'domain', IF(    CHAR_LENGTH(`servers1`.`hostname`), CONCAT_WS('',   `servers1`.`hostname`), '') as 'server', `subdomains`.`comments` as 'comments' FROM `subdomains` LEFT JOIN `domains` as domains1 ON `domains1`.`domain_name`=`subdomains`.`domain` LEFT JOIN `servers` as servers1 ON `servers1`.`id`=`subdomains`.`server` "
				],
				'server' => [
					'parent-table' => 'servers',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Subdomains <span class="hidden child-label-subdomains child-field-caption">(Server)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/domain_template.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'Subdomain', 2 => 'Domain', 3 => 'Server', 4 => 'Comments'],
					'display-field-names' => [1 => 'subdomain', 2 => 'domain', 3 => 'server', 4 => 'comments'],
					'sortable-fields' => [0 => '`subdomains`.`id`', 1 => 2, 2 => '`domains1`.`domain_name`', 3 => '`servers1`.`hostname`', 4 => 5],
					'records-per-page' => 10,
					'default-sort-by' => 2,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-subdomains',
					'template-printable' => 'children-subdomains-printable',
					'query' => "SELECT `subdomains`.`id` as 'id', `subdomains`.`subdomain` as 'subdomain', IF(    CHAR_LENGTH(`domains1`.`domain_name`), CONCAT_WS('',   `domains1`.`domain_name`), '') as 'domain', IF(    CHAR_LENGTH(`servers1`.`hostname`), CONCAT_WS('',   `servers1`.`hostname`), '') as 'server', `subdomains`.`comments` as 'comments' FROM `subdomains` LEFT JOIN `domains` as domains1 ON `domains1`.`domain_name`=`subdomains`.`domain` LEFT JOIN `servers` as servers1 ON `servers1`.`id`=`subdomains`.`server` "
				],
			],
			'registrars' => [
			],
			'dns_managers' => [
			],
			'mail_providers' => [
			],
			'clients' => [
			],
			'client_contacts' => [
				'client' => [
					'parent-table' => 'clients',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Client contacts <span class="hidden child-label-client_contacts child-field-caption">(Client)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/user_comment.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'Client', 2 => 'First name', 3 => 'Last name', 4 => 'Title', 5 => 'Mobile/Cellular', 6 => 'Work phone', 7 => 'Email', 8 => 'Comments'],
					'display-field-names' => [1 => 'client', 2 => 'first_name', 3 => 'last_name', 4 => 'title', 5 => 'mobile', 6 => 'work_phone', 7 => 'email', 8 => 'comments'],
					'sortable-fields' => [0 => '`client_contacts`.`id`', 1 => '`clients1`.`client`', 2 => 3, 3 => 4, 4 => 5, 5 => 6, 6 => 7, 7 => 8, 8 => 9],
					'records-per-page' => 10,
					'default-sort-by' => 1,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-client_contacts',
					'template-printable' => 'children-client_contacts-printable',
					'query' => "SELECT `client_contacts`.`id` as 'id', IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') as 'client', `client_contacts`.`first_name` as 'first_name', `client_contacts`.`last_name` as 'last_name', `client_contacts`.`title` as 'title', `client_contacts`.`mobile` as 'mobile', `client_contacts`.`work_phone` as 'work_phone', `client_contacts`.`email` as 'email', `client_contacts`.`comments` as 'comments' FROM `client_contacts` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`client_contacts`.`client` "
				],
			],
			'server_events' => [
				'server' => [
					'parent-table' => 'servers',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Server events <span class="hidden child-label-server_events child-field-caption">(Server)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/file_extension_log.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'Datetime', 2 => 'Server', 3 => 'Event', 4 => 'Details'],
					'display-field-names' => [1 => 'datetime', 2 => 'server', 3 => 'event', 4 => 'details'],
					'sortable-fields' => [0 => '`server_events`.`id`', 1 => '`server_events`.`datetime`', 2 => '`servers1`.`hostname`', 3 => 4, 4 => 5],
					'records-per-page' => 10,
					'default-sort-by' => 1,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-server_events',
					'template-printable' => 'children-server_events-printable',
					'query' => "SELECT `server_events`.`id` as 'id', if(`server_events`.`datetime`,date_format(`server_events`.`datetime`,'%d/%m/%Y %h:%i %p'),'') as 'datetime', IF(    CHAR_LENGTH(`servers1`.`hostname`), CONCAT_WS('',   `servers1`.`hostname`), '') as 'server', `server_events`.`event` as 'event', `server_events`.`details` as 'details' FROM `server_events` LEFT JOIN `servers` as servers1 ON `servers1`.`id`=`server_events`.`server` "
				],
			],
			'domain_events' => [
				'domain' => [
					'parent-table' => 'domains',
					'parent-primary-key' => 'domain_name',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Domain events <span class="hidden child-label-domain_events child-field-caption">(Domain)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/file_extension_log.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'Datetime', 2 => 'Domain', 3 => 'Event', 4 => 'Details'],
					'display-field-names' => [1 => 'datetime', 2 => 'domain', 3 => 'event', 4 => 'details'],
					'sortable-fields' => [0 => '`domain_events`.`id`', 1 => '`domain_events`.`datetime`', 2 => '`domains1`.`domain_name`', 3 => 4, 4 => 5],
					'records-per-page' => 10,
					'default-sort-by' => 1,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-domain_events',
					'template-printable' => 'children-domain_events-printable',
					'query' => "SELECT `domain_events`.`id` as 'id', if(`domain_events`.`datetime`,date_format(`domain_events`.`datetime`,'%d/%m/%Y %h:%i %p'),'') as 'datetime', IF(    CHAR_LENGTH(`domains1`.`domain_name`), CONCAT_WS('',   `domains1`.`domain_name`), '') as 'domain', `domain_events`.`event` as 'event', `domain_events`.`details` as 'details' FROM `domain_events` LEFT JOIN `domains` as domains1 ON `domains1`.`domain_name`=`domain_events`.`domain` "
				],
			],
			'subdomain_events' => [
				'subdomain' => [
					'parent-table' => 'subdomains',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Subdomain events <span class="hidden child-label-subdomain_events child-field-caption">(Subdomain)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/file_extension_log.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'Datetime', 2 => 'Subdomain', 3 => 'Event', 4 => 'Details'],
					'display-field-names' => [1 => 'datetime', 2 => 'subdomain', 3 => 'event', 4 => 'details'],
					'sortable-fields' => [0 => '`subdomain_events`.`id`', 1 => '`subdomain_events`.`datetime`', 2 => 3, 3 => 4, 4 => 5],
					'records-per-page' => 10,
					'default-sort-by' => 1,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-subdomain_events',
					'template-printable' => 'children-subdomain_events-printable',
					'query' => "SELECT `subdomain_events`.`id` as 'id', if(`subdomain_events`.`datetime`,date_format(`subdomain_events`.`datetime`,'%d/%m/%Y %h:%i %p'),'') as 'datetime', IF(    CHAR_LENGTH(`subdomains1`.`subdomain`) || CHAR_LENGTH(`domains1`.`domain_name`), CONCAT_WS('',   `subdomains1`.`subdomain`, '.', `domains1`.`domain_name`), '') as 'subdomain', `subdomain_events`.`event` as 'event', `subdomain_events`.`details` as 'details' FROM `subdomain_events` LEFT JOIN `subdomains` as subdomains1 ON `subdomains1`.`id`=`subdomain_events`.`subdomain` LEFT JOIN `domains` as domains1 ON `domains1`.`domain_name`=`subdomains1`.`domain` "
				],
			],
			'client_events' => [
				'client' => [
					'parent-table' => 'clients',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Client events <span class="hidden child-label-client_events child-field-caption">(Client)</span>',
					'auto-close' => false,
					'table-icon' => 'resources/table_icons/file_extension_log.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => [1 => 'Datetime', 2 => 'Client', 3 => 'Event', 4 => 'Details'],
					'display-field-names' => [1 => 'datetime', 2 => 'client', 3 => 'event', 4 => 'details'],
					'sortable-fields' => [0 => '`client_events`.`id`', 1 => '`client_events`.`datetime`', 2 => '`clients1`.`client`', 3 => 4, 4 => 5],
					'records-per-page' => 10,
					'default-sort-by' => 1,
					'default-sort-direction' => 'desc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-client_events',
					'template-printable' => 'children-client_events-printable',
					'query' => "SELECT `client_events`.`id` as 'id', if(`client_events`.`datetime`,date_format(`client_events`.`datetime`,'%d/%m/%Y %h:%i %p'),'') as 'datetime', IF(    CHAR_LENGTH(`clients1`.`client`), CONCAT_WS('',   `clients1`.`client`), '') as 'client', `client_events`.`event` as 'event', `client_events`.`details` as 'details' FROM `client_events` LEFT JOIN `clients` as clients1 ON `clients1`.`id`=`client_events`.`client` "
				],
			],
		];

	/*************************************/
	/* End of configuration */


	include_once(__DIR__ . '/lib.php');
	@header('Content-Type: text/html; charset=' . datalist_db_encoding);

	handle_maintenance();

	/**
	* dynamic configuration based on current user's permissions
	* $userPCConfig array is populated only with parent tables where the user has access to
	* at least one child table
	*/
	$userPCConfig = [];
	foreach($pcConfig as $pcChildTable => $ChildrenLookups) {
		$permChild = getTablePermissions($pcChildTable);
		if(!$permChild['view']) continue;

		foreach($ChildrenLookups as $ChildLookupField => $ChildConfig) {
			$permParent = getTablePermissions($ChildConfig['parent-table']);
			if(!$permParent['view']) continue;

			$userPCConfig[$pcChildTable][$ChildLookupField] = $pcConfig[$pcChildTable][$ChildLookupField];
			// show add new only if configured above AND the user has insert permission
			$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = ($permChild['insert'] && $pcConfig[$pcChildTable][$ChildLookupField]['display-add-new']);
		}
	}

	/* Receive, UTF-convert, and validate parameters */
	$ParentTable = Request::val('ParentTable'); // needed only with operation=show-children, will be validated in the processing code
	$ChildTable = Request::val('ChildTable');
		if(!in_array($ChildTable, array_keys($userPCConfig))) {
			/* defaults to first child table in config array if not provided */
			$ChildTable = current(array_keys($userPCConfig));
		}
		if(!$ChildTable) { die('<!-- No tables accessible to current user -->'); }
	$SelectedID = strip_tags(Request::val('SelectedID'));
	$ChildLookupField = Request::val('ChildLookupField');
		if(!in_array($ChildLookupField, array_keys($userPCConfig[$ChildTable]))) {
			/* defaults to first lookup in current child config array if not provided */
			$ChildLookupField = current(array_keys($userPCConfig[$ChildTable]));
		}

	if(function_exists('child_records_config')) {
		// $userPCConfig is passed by reference
		child_records_config($ChildTable, $ChildLookupField, $userPCConfig);
	}

	$currentConfig = $userPCConfig[$ChildTable][$ChildLookupField];
	if(empty($currentConfig))
		die('<!-- No tables accessible to current user -->');

	$Page = intval(Request::val('Page'));
		if($Page < 1) $Page = 1;
	$SortBy = (Request::val('SortBy') != '' ? abs(intval(Request::val('SortBy'))) : false);
		if(!in_array($SortBy, array_keys($currentConfig['sortable-fields']), true))
			$SortBy = $currentConfig['default-sort-by'];
	$SortDirection = strtolower(Request::val('SortDirection'));
		if(!in_array($SortDirection, ['asc', 'desc']))
			$SortDirection = $currentConfig['default-sort-direction'];
	$Operation = strtolower(Request::val('Operation'));
		if(!in_array($Operation, ['get-records', 'show-children', 'get-records-printable', 'show-children-printable']))
			$Operation = 'get-records';

	/* process requested operation */
	switch($Operation) {
		/************************************************/
		case 'show-children':
			/* populate HTML and JS content with children tabs */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups) {
				foreach($childLookups as $ChildLookupField => $childConfig) {
					if($childConfig['parent-table'] != $ParentTable) continue;

					$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\">" : '');

					$tabLabels .= "<li class=\"child-tab-label child-table-{$ChildTable} lookup-field-{$ChildLookupField} " . ($tabLabels ? '' : 'active') . "\">" .
							"<a href=\"#panel_{$ChildTable}-{$ChildLookupField}\" id=\"tab_{$ChildTable}-{$ChildLookupField}\" data-toggle=\"tab\">" .
								$TableIcon . $childConfig['tab-label'] .
								"<span class=\"badge child-count child-count-{$ChildTable}-{$ChildLookupField}\"></span>" .
							"</a>" .
						"</li>\n\t\t\t\t";

					$tabPanels .= "<div id=\"panel_{$ChildTable}-{$ChildLookupField}\" class=\"tab-pane" . ($tabPanels ? '' : ' active') . "\">" .
							"<i class=\"glyphicon glyphicon-refresh loop-rotate\"></i> " .
							"{$Translation['Loading ...']}" .
						"</div>\n\t\t\t\t";

					$tabLoaders .= "post('parent-children.php', " . json_encode([
							'ChildTable' => $ChildTable,
							'ChildLookupField' => $ChildLookupField,
							'SelectedID' => $SelectedID,
							'Page' => 1,
							'SortBy' => '',
							'SortDirection' => '',
							'Operation' => 'get-records'
						]) . ", 'panel_{$ChildTable}-{$ChildLookupField}');\n\t\t\t\t";
				}
			}

			if(!$tabLabels) { die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs">
				<ul class="nav nav-tabs">
					<?php echo $tabLabels; ?>
				</ul>
				<span id="pc-loading"></span>
			</div>
			<div class="tab-content"><?php echo $tabPanels; ?></div>

			<script>
				$j(function() {
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded) {
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>

					/* show child field caption on tab title in case the same child table appears more than once */
					$j('.child-field-caption').each(function() {
						var clss = $j(this).attr('class').split(/\s+/).reduce(function(rc, cc) {
							return (cc.match(/child-label-.*/) ? '.' + cc : rc);
						}, '');

						// if class occurs more than once, remove .hidden
						if($j(clss).length > 1) $j(clss).removeClass('hidden');
					})
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'show-children-printable':
			/* populate HTML and JS content with children buttons */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups) {
				foreach($childLookups as $ChildLookupField => $childConfig) {
					if($childConfig['parent-table'] != $ParentTable) continue;

					$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\">" : '');

					$tabLabels .= "<button type=\"button\" class=\"btn btn-default child-tab-print-toggler\" data-target=\"#panel_{$ChildTable}-{$ChildLookupField}\" id=\"tab_{$ChildTable}-{$ChildLookupField}\" data-toggle=\"collapse\">" .
							"{$TableIcon} {$childConfig['tab-label']}" .
							"<span class=\"badge child-count child-count-{$ChildTable}-{$ChildLookupField}\"></span>" .
						"</button>\n\t\t\t\t\t";

					$tabPanels .= "<div id=\"panel_{$ChildTable}-{$ChildLookupField}\" class=\"collapse child-panel-print\">" .
							"<i class=\"glyphicon glyphicon-refresh loop-rotate\"></i> " .
							$Translation['Loading ...'] .
						"</div>\n\t\t\t\t";

					$tabLoaders .= "post('parent-children.php', " . json_encode([
							'ChildTable' => $ChildTable,
							'ChildLookupField' => $ChildLookupField,
							'SelectedID' => $SelectedID,
							'Page' => 1,
							'SortBy' => '',
							'SortDirection' => '',
							'Operation' => 'get-records-printable'
						]) . ", 'panel_{$ChildTable}-{$ChildLookupField}');\n\t\t\t\t";
				}
			}

			if(!$tabLabels) { die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs" class="hidden-print">
				<div class="btn-group btn-group-lg">
					<?php echo $tabLabels; ?>
				</div>
				<span id="pc-loading"></span>
			</div>
			<div class="vspacer-lg"><?php echo $tabPanels; ?></div>

			<script>
				$j(function() {
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded) {
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'get-records-printable':
		default: /* default is 'get-records' */

			if($Operation == 'get-records-printable') {
				$currentConfig['records-per-page'] = 2000;
			}

			// build the user permissions limiter
			$permissionsWhere = $permissionsJoin = '';
			$permChild = getTablePermissions($ChildTable);
			if($permChild['view'] == 1) { // user can view only his own records
				$permissionsWhere = "`$ChildTable`.`{$currentConfig['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
			} elseif($permChild['view'] == 2) { // user can view only his group's records
				$permissionsWhere = "`$ChildTable`.`{$currentConfig['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
			} elseif($permChild['view'] == 3) { // user can view all records
				/* that's the only case remaining ... no need to modify the query in this case */
			}
			$permissionsJoin = ($permissionsWhere ? ", `membership_userrecords`" : '');

			// build the count query
			$forcedWhere = $currentConfig['forced-where'];
			$query = 
				preg_replace('/^select .* from /i', 'SELECT count(1) FROM ', $currentConfig['query']) .
				$permissionsJoin . " WHERE " .
				($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
				($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
				"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'";
			$totalMatches = sqlValue($query);

			// make sure $Page is <= max pages
			$maxPage = ceil($totalMatches / $currentConfig['records-per-page']);
			if($Page > $maxPage) { $Page = $maxPage; }

			// initiate output data array
			$data = [
				'config' => $currentConfig,
				'parameters' => [
					'ChildTable' => $ChildTable,
					'ChildLookupField' => $ChildLookupField,
					'SelectedID' => $SelectedID,
					'Page' => $Page,
					'SortBy' => $SortBy,
					'SortDirection' => $SortDirection,
					'Operation' => $Operation,
				],
				'records' => [],
				'totalMatches' => $totalMatches
			];

			// build the data query
			if($totalMatches) { // if we have at least one record, proceed with fetching data
				$startRecord = $currentConfig['records-per-page'] * ($Page - 1);
				$data['query'] = 
					$currentConfig['query'] .
					$permissionsJoin . " WHERE " .
					($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
					($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
					"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'" . 
					($SortBy !== false && $currentConfig['sortable-fields'][$SortBy] ? " ORDER BY {$currentConfig['sortable-fields'][$SortBy]} $SortDirection" : '') .
					" LIMIT $startRecord, {$currentConfig['records-per-page']}";
				$res = sql($data['query'], $eo);
				while($row = db_fetch_row($res)) {
					$data['records'][$row[$currentConfig['child-primary-key-index']]] = $row;
				}
			} else { // if no matching records
				$startRecord = 0;
			}

			if($Operation == 'get-records-printable') {
				$response = loadView($currentConfig['template-printable'], $data);
			} else {
				$response = loadView($currentConfig['template'], $data);
			}

			// change name space to ensure uniqueness
			$uniqueNameSpace = $ChildTable.ucfirst($ChildLookupField).'GetRecords';
			echo str_replace("{$ChildTable}GetChildrenRecordsList", $uniqueNameSpace, $response);
		/************************************************/
	}
