<?php

// Data functions (insert, update, delete, form) for table servers

// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function servers_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('servers');
	if(!$arrPerm['insert']) return false;

	$data = [
		'ip_address' => Request::val('ip_address', ''),
		'client' => Request::lookup('client', ''),
		'hosted_at' => Request::lookup('hosted_at', ''),
		'data_center' => Request::lookup('data_center', ''),
		'hostname' => Request::val('hostname', ''),
		'ram' => Request::val('ram', ''),
		'storage' => Request::val('storage', ''),
		'os' => Request::lookup('os', ''),
		'comments' => Request::val('comments', ''),
	];


	// hook: servers_before_insert
	if(function_exists('servers_before_insert')) {
		$args = [];
		if(!servers_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('servers', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('servers', $recID, calculated_fields()['servers']);

	// hook: servers_after_insert
	if(function_exists('servers_after_insert')) {
		$res = sql("SELECT * FROM `servers` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!servers_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('servers', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) servers_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function servers_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function servers_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('servers', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: servers_before_delete
	if(function_exists('servers_before_delete')) {
		$args = [];
		if(!servers_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: subdomains
	$res = sql("SELECT `id` FROM `servers` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `subdomains` WHERE `server`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'subdomains', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'subdomains', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'servers_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'servers_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: server_events
	$res = sql("SELECT `id` FROM `servers` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `server_events` WHERE `server`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'server_events', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'server_events', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'servers_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'servers_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `servers` WHERE `id`='{$selected_id}'", $eo);

	// hook: servers_after_delete
	if(function_exists('servers_after_delete')) {
		$args = [];
		servers_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='servers' AND `pkValue`='{$selected_id}'", $eo);
}

function servers_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('servers', $selected_id, 'edit')) return false;

	$data = [
		'ip_address' => Request::val('ip_address', ''),
		'client' => Request::lookup('client', ''),
		'hosted_at' => Request::lookup('hosted_at', ''),
		'data_center' => Request::lookup('data_center', ''),
		'hostname' => Request::val('hostname', ''),
		'ram' => Request::val('ram', ''),
		'storage' => Request::val('storage', ''),
		'os' => Request::lookup('os', ''),
		'comments' => Request::val('comments', ''),
	];

	// get existing values
	$old_data = getRecord('servers', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: servers_before_update
	if(function_exists('servers_before_update')) {
		$args = ['old_data' => $old_data];
		if(!servers_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'servers', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="servers_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('servers', $data['selectedID'], calculated_fields()['servers']);

	// hook: servers_after_update
	if(function_exists('servers_after_update')) {
		$res = sql("SELECT * FROM `servers` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!servers_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='servers' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function servers_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('servers');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_client = Request::val('filterer_client');
	$filterer_hosted_at = Request::val('filterer_hosted_at');
	$filterer_data_center = Request::val('filterer_data_center');
	$filterer_os = Request::val('filterer_os');

	// populate filterers, starting from children to grand-parents
	if($filterer_data_center && !$filterer_hosted_at) $filterer_hosted_at = sqlValue("select hosting_provider from data_centers where id='" . makeSafe($filterer_data_center) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: client
	$combo_client = new DataCombo;
	// combobox: hosted_at
	$combo_hosted_at = new DataCombo;
	// combobox: data_center, filterable by: hosted_at
	$combo_data_center = new DataCombo;
	// combobox: os
	$combo_os = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('servers', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('servers', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('servers', $selected_id, 'delete');

		$res = sql("SELECT * FROM `servers` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'servers_view.php', false);
		}
		$combo_client->SelectedData = $row['client'];
		$combo_hosted_at->SelectedData = $row['hosted_at'];
		$combo_data_center->SelectedData = $row['data_center'];
		$combo_os->SelectedData = $row['os'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_client->SelectedData = $filterer_client;
		$combo_hosted_at->SelectedData = $filterer_hosted_at;
		$combo_data_center->SelectedData = $filterer_data_center;
		$combo_os->SelectedData = $filterer_os;
	}
	$combo_client->HTML = '<span id="client-container' . $rnd1 . '"></span><input type="hidden" name="client" id="client' . $rnd1 . '" value="' . html_attr($combo_client->SelectedData) . '">';
	$combo_client->MatchText = '<span id="client-container-readonly' . $rnd1 . '"></span><input type="hidden" name="client" id="client' . $rnd1 . '" value="' . html_attr($combo_client->SelectedData) . '">';
	$combo_hosted_at->HTML = '<span id="hosted_at-container' . $rnd1 . '"></span><input type="hidden" name="hosted_at" id="hosted_at' . $rnd1 . '" value="' . html_attr($combo_hosted_at->SelectedData) . '">';
	$combo_hosted_at->MatchText = '<span id="hosted_at-container-readonly' . $rnd1 . '"></span><input type="hidden" name="hosted_at" id="hosted_at' . $rnd1 . '" value="' . html_attr($combo_hosted_at->SelectedData) . '">';
	$combo_data_center->HTML = '<span id="data_center-container' . $rnd1 . '"></span><input type="hidden" name="data_center" id="data_center' . $rnd1 . '" value="' . html_attr($combo_data_center->SelectedData) . '">';
	$combo_data_center->MatchText = '<span id="data_center-container-readonly' . $rnd1 . '"></span><input type="hidden" name="data_center" id="data_center' . $rnd1 . '" value="' . html_attr($combo_data_center->SelectedData) . '">';
	$combo_os->HTML = '<span id="os-container' . $rnd1 . '"></span><input type="hidden" name="os" id="os' . $rnd1 . '" value="' . html_attr($combo_os->SelectedData) . '">';
	$combo_os->MatchText = '<span id="os-container-readonly' . $rnd1 . '"></span><input type="hidden" name="os" id="os' . $rnd1 . '" value="' . html_attr($combo_os->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_client__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['client'] : htmlspecialchars($filterer_client, ENT_QUOTES)); ?>"};
		AppGini.current_hosted_at__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['hosted_at'] : htmlspecialchars($filterer_hosted_at, ENT_QUOTES)); ?>"};
		AppGini.current_data_center__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['data_center'] : htmlspecialchars($filterer_data_center, ENT_QUOTES)); ?>"};
		AppGini.current_os__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['os'] : htmlspecialchars($filterer_os, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(client_reload__RAND__) == 'function') client_reload__RAND__();
				if(typeof(hosted_at_reload__RAND__) == 'function') hosted_at_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(data_center_reload__RAND__) == \'function\') data_center_reload__RAND__(AppGini.current_hosted_at__RAND__.value);' : ''); ?>
				if(typeof(os_reload__RAND__) == 'function') os_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function client_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#client-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_client__RAND__.value, t: 'servers', f: 'client' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="client"]').val(resp.results[0].id);
							$j('[id=client-container-readonly__RAND__]').html('<span class="match-text" id="client-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=clients_view_parent]').hide(); } else { $j('.btn[id=clients_view_parent]').show(); }


							if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'servers', f: 'client' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_client__RAND__.value = e.added.id;
				AppGini.current_client__RAND__.text = e.added.text;
				$j('[name="client"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=clients_view_parent]').hide(); } else { $j('.btn[id=clients_view_parent]').show(); }


				if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
			});

			if(!$j("#client-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_client__RAND__.value, t: 'servers', f: 'client' },
					success: function(resp) {
						$j('[name="client"]').val(resp.results[0].id);
						$j('[id=client-container-readonly__RAND__]').html('<span class="match-text" id="client-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=clients_view_parent]').hide(); } else { $j('.btn[id=clients_view_parent]').show(); }

						if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_client__RAND__.value, t: 'servers', f: 'client' },
				success: function(resp) {
					$j('[id=client-container__RAND__], [id=client-container-readonly__RAND__]').html('<span class="match-text" id="client-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=clients_view_parent]').hide(); } else { $j('.btn[id=clients_view_parent]').show(); }

					if(typeof(client_update_autofills__RAND__) == 'function') client_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function hosted_at_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#hosted_at-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_hosted_at__RAND__.value, t: 'servers', f: 'hosted_at' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="hosted_at"]').val(resp.results[0].id);
							$j('[id=hosted_at-container-readonly__RAND__]').html('<span class="match-text" id="hosted_at-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=hosting_providers_view_parent]').hide(); } else { $j('.btn[id=hosting_providers_view_parent]').show(); }

						if(typeof(data_center_reload__RAND__) == 'function') data_center_reload__RAND__(AppGini.current_hosted_at__RAND__.value);

							if(typeof(hosted_at_update_autofills__RAND__) == 'function') hosted_at_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'servers', f: 'hosted_at' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_hosted_at__RAND__.value = e.added.id;
				AppGini.current_hosted_at__RAND__.text = e.added.text;
				$j('[name="hosted_at"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=hosting_providers_view_parent]').hide(); } else { $j('.btn[id=hosting_providers_view_parent]').show(); }

						if(typeof(data_center_reload__RAND__) == 'function') data_center_reload__RAND__(AppGini.current_hosted_at__RAND__.value);

				if(typeof(hosted_at_update_autofills__RAND__) == 'function') hosted_at_update_autofills__RAND__();
			});

			if(!$j("#hosted_at-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_hosted_at__RAND__.value, t: 'servers', f: 'hosted_at' },
					success: function(resp) {
						$j('[name="hosted_at"]').val(resp.results[0].id);
						$j('[id=hosted_at-container-readonly__RAND__]').html('<span class="match-text" id="hosted_at-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=hosting_providers_view_parent]').hide(); } else { $j('.btn[id=hosting_providers_view_parent]').show(); }

						if(typeof(hosted_at_update_autofills__RAND__) == 'function') hosted_at_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_hosted_at__RAND__.value, t: 'servers', f: 'hosted_at' },
				success: function(resp) {
					$j('[id=hosted_at-container__RAND__], [id=hosted_at-container-readonly__RAND__]').html('<span class="match-text" id="hosted_at-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=hosting_providers_view_parent]').hide(); } else { $j('.btn[id=hosting_providers_view_parent]').show(); }

					if(typeof(hosted_at_update_autofills__RAND__) == 'function') hosted_at_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function data_center_reload__RAND__(filterer_hosted_at) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#data_center-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_hosted_at: filterer_hosted_at, id: AppGini.current_data_center__RAND__.value, t: 'servers', f: 'data_center' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="data_center"]').val(resp.results[0].id);
							$j('[id=data_center-container-readonly__RAND__]').html('<span class="match-text" id="data_center-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=data_centers_view_parent]').hide(); } else { $j('.btn[id=data_centers_view_parent]').show(); }


							if(typeof(data_center_update_autofills__RAND__) == 'function') data_center_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_hosted_at: filterer_hosted_at, s: term, p: page, t: 'servers', f: 'data_center' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_data_center__RAND__.value = e.added.id;
				AppGini.current_data_center__RAND__.text = e.added.text;
				$j('[name="data_center"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=data_centers_view_parent]').hide(); } else { $j('.btn[id=data_centers_view_parent]').show(); }


				if(typeof(data_center_update_autofills__RAND__) == 'function') data_center_update_autofills__RAND__();
			});

			if(!$j("#data_center-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_data_center__RAND__.value, t: 'servers', f: 'data_center' },
					success: function(resp) {
						$j('[name="data_center"]').val(resp.results[0].id);
						$j('[id=data_center-container-readonly__RAND__]').html('<span class="match-text" id="data_center-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=data_centers_view_parent]').hide(); } else { $j('.btn[id=data_centers_view_parent]').show(); }

						if(typeof(data_center_update_autofills__RAND__) == 'function') data_center_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_data_center__RAND__.value, t: 'servers', f: 'data_center' },
				success: function(resp) {
					$j('[id=data_center-container__RAND__], [id=data_center-container-readonly__RAND__]').html('<span class="match-text" id="data_center-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=data_centers_view_parent]').hide(); } else { $j('.btn[id=data_centers_view_parent]').show(); }

					if(typeof(data_center_update_autofills__RAND__) == 'function') data_center_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function os_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#os-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_os__RAND__.value, t: 'servers', f: 'os' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="os"]').val(resp.results[0].id);
							$j('[id=os-container-readonly__RAND__]').html('<span class="match-text" id="os-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=operating_systems_view_parent]').hide(); } else { $j('.btn[id=operating_systems_view_parent]').show(); }


							if(typeof(os_update_autofills__RAND__) == 'function') os_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'servers', f: 'os' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_os__RAND__.value = e.added.id;
				AppGini.current_os__RAND__.text = e.added.text;
				$j('[name="os"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=operating_systems_view_parent]').hide(); } else { $j('.btn[id=operating_systems_view_parent]').show(); }


				if(typeof(os_update_autofills__RAND__) == 'function') os_update_autofills__RAND__();
			});

			if(!$j("#os-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_os__RAND__.value, t: 'servers', f: 'os' },
					success: function(resp) {
						$j('[name="os"]').val(resp.results[0].id);
						$j('[id=os-container-readonly__RAND__]').html('<span class="match-text" id="os-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=operating_systems_view_parent]').hide(); } else { $j('.btn[id=operating_systems_view_parent]').show(); }

						if(typeof(os_update_autofills__RAND__) == 'function') os_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_os__RAND__.value, t: 'servers', f: 'os' },
				success: function(resp) {
					$j('[id=os-container__RAND__], [id=os-container-readonly__RAND__]').html('<span class="match-text" id="os-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=operating_systems_view_parent]').hide(); } else { $j('.btn[id=operating_systems_view_parent]').show(); }

					if(typeof(os_update_autofills__RAND__) == 'function') os_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/servers_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/servers_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Server details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return servers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return servers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return servers_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#ip_address').replaceWith('<div class=\"form-control-static\" id=\"ip_address\">' + (jQuery('#ip_address').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#client').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#client_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#hosted_at').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#hosted_at_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#data_center').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#data_center_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#hostname').replaceWith('<div class=\"form-control-static\" id=\"hostname\">' + (jQuery('#hostname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#ram').replaceWith('<div class=\"form-control-static\" id=\"ram\">' + (jQuery('#ram').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#storage').replaceWith('<div class=\"form-control-static\" id=\"storage\">' + (jQuery('#storage').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#os').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#os_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(client)%%>', $combo_client->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(client)%%>', $combo_client->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(client)%%>', urlencode($combo_client->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(hosted_at)%%>', $combo_hosted_at->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(hosted_at)%%>', $combo_hosted_at->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(hosted_at)%%>', urlencode($combo_hosted_at->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(data_center)%%>', $combo_data_center->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(data_center)%%>', $combo_data_center->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(data_center)%%>', urlencode($combo_data_center->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(os)%%>', $combo_os->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(os)%%>', $combo_os->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(os)%%>', urlencode($combo_os->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['client' => ['clients', 'Client'], 'hosted_at' => ['hosting_providers', 'Hosted at'], 'data_center' => ['data_centers', 'Data center'], 'os' => ['operating_systems', 'OS'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ip_address)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(client)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hosted_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(data_center)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hostname)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ram)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(storage)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(os)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(comments)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ip_address)%%>', safe_html($urow['ip_address']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ip_address)%%>', html_attr($row['ip_address']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ip_address)%%>', urlencode($urow['ip_address']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(client)%%>', safe_html($urow['client']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(client)%%>', html_attr($row['client']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(client)%%>', urlencode($urow['client']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(hosted_at)%%>', safe_html($urow['hosted_at']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(hosted_at)%%>', html_attr($row['hosted_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hosted_at)%%>', urlencode($urow['hosted_at']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(data_center)%%>', safe_html($urow['data_center']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(data_center)%%>', html_attr($row['data_center']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(data_center)%%>', urlencode($urow['data_center']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(hostname)%%>', safe_html($urow['hostname']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(hostname)%%>', html_attr($row['hostname']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hostname)%%>', urlencode($urow['hostname']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ram)%%>', safe_html($urow['ram']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ram)%%>', html_attr($row['ram']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ram)%%>', urlencode($urow['ram']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(storage)%%>', safe_html($urow['storage']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(storage)%%>', html_attr($row['storage']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(storage)%%>', urlencode($urow['storage']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(os)%%>', safe_html($urow['os']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(os)%%>', html_attr($row['os']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(os)%%>', urlencode($urow['os']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(comments)%%>', '<textarea name="comments" id="comments" rows="5">' . safe_html(htmlspecialchars_decode($row['comments'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(comments)%%>', '<div id="comments" class="form-control-static">' . $row['comments'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(comments)%%>', nl2br($row['comments']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(comments)%%>', urlencode($urow['comments']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ip_address)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ip_address)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(client)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(client)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hosted_at)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hosted_at)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(data_center)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(data_center)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hostname)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hostname)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ram)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ram)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(storage)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(storage)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(os)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(os)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(comments)%%>', '<textarea name="comments" id="comments" rows="5"></textarea>', $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('servers');
	if($selected_id) {
		$jdata = get_joined_record('servers', $selected_id);
		if($jdata === false) $jdata = get_defaults('servers');
		$rdata = $row;
	}
	$templateCode .= loadView('servers-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: servers_dv
	if(function_exists('servers_dv')) {
		$args = [];
		servers_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}