<?php

// Data functions (insert, update, delete, form) for table subdomains

// This script and data application were generated by AppGini 23.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function subdomains_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('subdomains');
	if(!$arrPerm['insert']) return false;

	$data = [
		'subdomain' => Request::val('subdomain', ''),
		'domain' => Request::lookup('domain', ''),
		'server' => Request::lookup('server', ''),
		'comments' => Request::val('comments', ''),
	];


	// hook: subdomains_before_insert
	if(function_exists('subdomains_before_insert')) {
		$args = [];
		if(!subdomains_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('subdomains', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('subdomains', $recID, calculated_fields()['subdomains']);

	// hook: subdomains_after_insert
	if(function_exists('subdomains_after_insert')) {
		$res = sql("SELECT * FROM `subdomains` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!subdomains_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('subdomains', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) subdomains_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function subdomains_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function subdomains_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('subdomains', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: subdomains_before_delete
	if(function_exists('subdomains_before_delete')) {
		$args = [];
		if(!subdomains_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: subdomain_events
	$res = sql("SELECT `id` FROM `subdomains` WHERE `id`='{$selected_id}'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `subdomain_events` WHERE `subdomain`='" . makeSafe($id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'subdomain_events', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'subdomain_events', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'subdomains_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'subdomains_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `subdomains` WHERE `id`='{$selected_id}'", $eo);

	// hook: subdomains_after_delete
	if(function_exists('subdomains_after_delete')) {
		$args = [];
		subdomains_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='subdomains' AND `pkValue`='{$selected_id}'", $eo);
}

function subdomains_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('subdomains', $selected_id, 'edit')) return false;

	$data = [
		'subdomain' => Request::val('subdomain', ''),
		'domain' => Request::lookup('domain', ''),
		'server' => Request::lookup('server', ''),
		'comments' => Request::val('comments', ''),
	];

	// get existing values
	$old_data = getRecord('subdomains', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: subdomains_before_update
	if(function_exists('subdomains_before_update')) {
		$args = ['old_data' => $old_data];
		if(!subdomains_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'subdomains', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="subdomains_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('subdomains', $data['selectedID'], calculated_fields()['subdomains']);

	// hook: subdomains_after_update
	if(function_exists('subdomains_after_update')) {
		$res = sql("SELECT * FROM `subdomains` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!subdomains_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='subdomains' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function subdomains_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('subdomains');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_domain = Request::val('filterer_domain');
	$filterer_server = Request::val('filterer_server');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: domain
	$combo_domain = new DataCombo;
	// combobox: server
	$combo_server = new DataCombo;

	if($selected_id) {
		if(!check_record_permission('subdomains', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('subdomains', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('subdomains', $selected_id, 'delete');

		$res = sql("SELECT * FROM `subdomains` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'subdomains_view.php', false);
		}
		$combo_domain->SelectedData = $row['domain'];
		$combo_server->SelectedData = $row['server'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_domain->SelectedData = $filterer_domain;
		$combo_server->SelectedData = $filterer_server;
	}
	$combo_domain->HTML = '<span id="domain-container' . $rnd1 . '"></span><input type="hidden" name="domain" id="domain' . $rnd1 . '" value="' . html_attr($combo_domain->SelectedData) . '">';
	$combo_domain->MatchText = '<span id="domain-container-readonly' . $rnd1 . '"></span><input type="hidden" name="domain" id="domain' . $rnd1 . '" value="' . html_attr($combo_domain->SelectedData) . '">';
	$combo_server->HTML = '<span id="server-container' . $rnd1 . '"></span><input type="hidden" name="server" id="server' . $rnd1 . '" value="' . html_attr($combo_server->SelectedData) . '">';
	$combo_server->MatchText = '<span id="server-container-readonly' . $rnd1 . '"></span><input type="hidden" name="server" id="server' . $rnd1 . '" value="' . html_attr($combo_server->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_domain__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['domain'] : htmlspecialchars($filterer_domain, ENT_QUOTES)); ?>"};
		AppGini.current_server__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['server'] : htmlspecialchars($filterer_server, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(domain_reload__RAND__) == 'function') domain_reload__RAND__();
				if(typeof(server_reload__RAND__) == 'function') server_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function domain_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#domain-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_domain__RAND__.value, t: 'subdomains', f: 'domain' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="domain"]').val(resp.results[0].id);
							$j('[id=domain-container-readonly__RAND__]').html('<span class="match-text" id="domain-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=domains_view_parent]').hide(); } else { $j('.btn[id=domains_view_parent]').show(); }


							if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'subdomains', f: 'domain' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_domain__RAND__.value = e.added.id;
				AppGini.current_domain__RAND__.text = e.added.text;
				$j('[name="domain"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=domains_view_parent]').hide(); } else { $j('.btn[id=domains_view_parent]').show(); }


				if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
			});

			if(!$j("#domain-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_domain__RAND__.value, t: 'subdomains', f: 'domain' },
					success: function(resp) {
						$j('[name="domain"]').val(resp.results[0].id);
						$j('[id=domain-container-readonly__RAND__]').html('<span class="match-text" id="domain-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=domains_view_parent]').hide(); } else { $j('.btn[id=domains_view_parent]').show(); }

						if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_domain__RAND__.value, t: 'subdomains', f: 'domain' },
				success: function(resp) {
					$j('[id=domain-container__RAND__], [id=domain-container-readonly__RAND__]').html('<span class="match-text" id="domain-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=domains_view_parent]').hide(); } else { $j('.btn[id=domains_view_parent]').show(); }

					if(typeof(domain_update_autofills__RAND__) == 'function') domain_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function server_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#server-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_server__RAND__.value, t: 'subdomains', f: 'server' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="server"]').val(resp.results[0].id);
							$j('[id=server-container-readonly__RAND__]').html('<span class="match-text" id="server-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=servers_view_parent]').hide(); } else { $j('.btn[id=servers_view_parent]').show(); }


							if(typeof(server_update_autofills__RAND__) == 'function') server_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'subdomains', f: 'server' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_server__RAND__.value = e.added.id;
				AppGini.current_server__RAND__.text = e.added.text;
				$j('[name="server"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=servers_view_parent]').hide(); } else { $j('.btn[id=servers_view_parent]').show(); }


				if(typeof(server_update_autofills__RAND__) == 'function') server_update_autofills__RAND__();
			});

			if(!$j("#server-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_server__RAND__.value, t: 'subdomains', f: 'server' },
					success: function(resp) {
						$j('[name="server"]').val(resp.results[0].id);
						$j('[id=server-container-readonly__RAND__]').html('<span class="match-text" id="server-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=servers_view_parent]').hide(); } else { $j('.btn[id=servers_view_parent]').show(); }

						if(typeof(server_update_autofills__RAND__) == 'function') server_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_server__RAND__.value, t: 'subdomains', f: 'server' },
				success: function(resp) {
					$j('[id=server-container__RAND__], [id=server-container-readonly__RAND__]').html('<span class="match-text" id="server-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=servers_view_parent]').hide(); } else { $j('.btn[id=servers_view_parent]').show(); }

					if(typeof(server_update_autofills__RAND__) == 'function') server_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/subdomains_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/subdomains_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Subdomain details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return subdomains_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return subdomains_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return subdomains_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#subdomain').replaceWith('<div class=\"form-control-static\" id=\"subdomain\">' + (jQuery('#subdomain').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#domain').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#domain_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#server').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#server_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(domain)%%>', $combo_domain->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(domain)%%>', $combo_domain->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(domain)%%>', urlencode($combo_domain->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(server)%%>', $combo_server->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(server)%%>', $combo_server->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(server)%%>', urlencode($combo_server->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['domain' => ['domains', 'Domain'], 'server' => ['servers', 'Server'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(subdomain)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(domain)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(server)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(comments)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(subdomain)%%>', safe_html($urow['subdomain']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(subdomain)%%>', html_attr($row['subdomain']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subdomain)%%>', urlencode($urow['subdomain']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(domain)%%>', safe_html($urow['domain']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(domain)%%>', html_attr($row['domain']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(domain)%%>', urlencode($urow['domain']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(server)%%>', safe_html($urow['server']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(server)%%>', html_attr($row['server']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(server)%%>', urlencode($urow['server']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(comments)%%>', '<textarea name="comments" id="comments" rows="5">' . safe_html(htmlspecialchars_decode($row['comments'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(comments)%%>', '<div id="comments" class="form-control-static">' . $row['comments'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(comments)%%>', nl2br($row['comments']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(comments)%%>', urlencode($urow['comments']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(subdomain)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subdomain)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(domain)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(domain)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(server)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(server)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(comments)%%>', '<textarea name="comments" id="comments" rows="5"></textarea>', $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('subdomains');
	if($selected_id) {
		$jdata = get_joined_record('subdomains', $selected_id);
		if($jdata === false) $jdata = get_defaults('subdomains');
		$rdata = $row;
	}
	$templateCode .= loadView('subdomains-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: subdomains_dv
	if(function_exists('subdomains_dv')) {
		$args = [];
		subdomains_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}